USE master
GO
ALTER DATABASE Tpd SET OFFLINE WITH ROLLBACK IMMEDIATE
GO

-- enable read committed snapshot
ALTER DATABASE Tpd SET READ_COMMITTED_SNAPSHOT ON WITH ROLLBACK IMMEDIATE
GO

-- bring database back online
USE master
GO

ALTER DATABASE Tpd SET ONLINE
GO